version: '2'
services:
  vwauth:
    extends:
      file: docker-compose.yml
      service: vwauth
    env_file: ./.env.dev
    volumes:
      - /db:/db
      # For development thorugh mounting the source dir as a volume
      # This should be path the vwadaptor source code
      # If using windows docker client, first copy the code to
      # docker machine and then mount volume like follows
      #- /home/docker/vw-auth:/var/www/vw-auth
    depends_on:
      - vwmail

  vwmail:
    extends:
      file: docker-compose.yml
      service: vwmail
    command: bin/maildev --web 80 --smtp 25 --verbose
    ports:
      - "1080:80"
